FROM python:3.9-slim

WORKDIR /app

# Copy en install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app
COPY . .

# Run als root (simpel, werkt altijd)
EXPOSE 5000

# Direct gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 0 app:app
